### PR TITLE
refactor: handle overflow errors and add fuzzing

### PR DESCRIPTION
**Pull request by sno2**
I understand that the overflow is documented. However, I think that it is a bit unrealistic to assume that users will validate that the addresses are valid. Adding this error variant should reduce the likelihood of vulnerabilities due to improper use of this crate.

### CODE REVIEW

**Comment by sno2** [comment]
> ## Panics
> If slices can't be chunked into arrays of the right sizes

I also have been unable to reproduce this panic by fuzzing the library after 30 minutes.

**Comment by tommy-gilligan** [comment]
Thank you for the PR!  I'm happy with your changes and I think it underlines how meaningless clippy's help can be sometimes.  I opted into pedantic and nursery so I guess I'm kind of asking for that.

There are already conflicts that need to be resolved, so I'll push an update on base branch to disable missing-panics-doc
I'm very interested in how you've done fuzzing here.  It would be lovely to include this in CI.

**Comment by sno2** [comment]
Yeah, did not realize that clippy was whining about that. You can see the fuzzing github actions that I created [here](https://github.com/sno2/uf2-decode/actions/runs/6231300795/job/16912654199).

**Comment by tommy-gilligan** [comment]
TYSM <3

**Pull request merged**
